### PR TITLE
Member interface implementation

### PR DESCRIPTION
**Pull request by JoshuaSaikali**

### CODE REVIEW

**Review by JoshuaSaikali — COMMENTED** [review]
When rescheduling the PT session :
- check for when start time input is before trainer availability (end-time is in range of availability)
- check for when end-time input is after trainer availability (start-time is in the range of availability)

when updating the member's profile, if nothing is entered for all of the inputs, then the program crashes

when trying to register for a class and no id is entered, then the program crashes

when rescheduling PT session and no id is entered, the program crashes

**Comment by JoshuaSaikali** [comment]
when updating the member's profile, if nothing is entered for any of the inputs, then the program crashes

**Comment by JoshuaSaikali** [comment]
when trying to register for a class and no id is entered, then the program crashes

**Comment by JoshuaSaikali** [comment]
when rescheduling PT session and no id is entered, the program crashes

**Comment by WillMarcuss** [comment]
| Requirement | Status |
|--------|--------|
| check for when end-time input is after trainer availability (start-time is in the range of availability) | Fixed and ready for test |
| check for when start time input is before trainer availability (end-time is in range of availability) | Fixed and ready for test |
| when updating the member's profile, if nothing is entered for all of the inputs, then the program crashes | Fixed and ready for test |
| when trying to register for a class and no id is entered, then the program crashes | Fixed and ready for test |
| when rescheduling PT session and no id is entered, the program crashes | Fixed and ready for test | 

@JoshuaSaikali please take a look, I went back over and fixed the above issues, should be all good with my newest commits. From what I have checked, I seemed to have fixed all the empty input cases for member functions.

**Comment by JoshuaSaikali** [comment]
Looks good! Feel free to merge whenever!

**Pull request merged**
